before_script:
  - apt-get update -qq && apt-get install -y -qq sqlite3 libsqlite3-dev nodejs
  - ruby -v
  - which ruby
  - gem install bundler --no-ri --no-rdoc
  - bundle install

test:
  script:
    - echo "This is test stage"

build:
  script:
    - echo "This is the build stage"

staging:
  type: deploy
  script:
    - echo "This is the staging stage"
    - cap deploy staging
  only:
    - stage