cache:
  paths:
    - vendor/bundle

before_script:
  - whoami
  - pwd
  - ruby -v
  - which ruby
  - ls -l
  - git clone https://github.com/rbenv/rbenv.git ~/.rbenv
  - echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bash_profile
  - ~/.rbenv/bin/rbenv init -
  - gem install bundler
  - rbenv install --skip-existing `cat .ruby-version`
  - bundle install --path vendor/bundle

build:
  stage: build
  script:
    - echo "This is the build stage"

test:
  stage: test
  script:
    - echo "This is test stage"

staging:
  stage: deploy
  script:
    - echo "This is the staging stage"
    - cap staging deploy
  only:
    - stage