before_script:
  - echo "This is the before_script"
  - echo $PATH
  - ruby -v
  - which ruby
  - rbenv install --skip-existing `cat .ruby-version`
  - rbenv rehash
  - gem install bundler
  - bundle install

build:
  stage: build
  script:
    - echo "This is the build stage"

test:
  stage: test
  script:
    - echo "This is test stage"

staging:
  stage: deploy
  script:
    - echo "This is the staging stage"
    - bundle exec cap staging deploy
  only:
    - stage