image: ruby:2.4


cache:
  paths:
    - /cache

before_script:
  - whoami
  - pwd
  - ruby -v
  - which ruby
  - ls -l

build:
  stage: build
  script:
    - echo "This is the build stage"
    - bundle install --path /cache

test:
  stage: test
  script:
    - echo "This is test stage"

staging:
  stage: deploy
  script:
    - echo "This is the staging stage"
    - apt-get update
    - apt-get install -y -qq openssh-server
    - cap staging deploy
  only:
    - stage