cache:
  paths:
    - vendor/bundle

before_script:
  - ruby -v
  - which ruby
  - rbenv install --skip-existing `cat .ruby-version`
  - gem install bundler
  - bundle install --path vendor/bundle
  - git clone https://git.caseydris.co/casey/runner-steps.git steps
  - chmod -R 775 steps
  - export CI_RELEASE=$(date +%Y%m%d%H%M%S)

build:
  stage: build
  script:
    - echo "This is the build stage"

test:
  stage: test
  script:
    - echo "This is test stage"

staging:
  stage: deploy
  script:
    - echo "This is the staging stage"
    - steps/deploy $STAGE_PATH $CI_RELEASE
  only:
    - stage