cache:
  paths:
    - vendor/bundle

before_script:
  - echo "This is the before_script"
  - echo $PATH
  - ruby -v
  - which ruby
  - rbenv install --skip-existing `cat .ruby-version`
  - rbenv rehash
  - gem install bundler
  - bundle update --path vendor/bundle
  - git clone https://git.caseydris.co/casey/rails-runner.git steps
  - chmod -R 775 steps
  - export CI_RELEASE=$(date +%Y%m%d%H%M%S)

build:
  stage: build
  script:
    - echo "This is the build stage"

test:
  stage: test
  script:
    - echo "This is test stage"

staging:
  stage: deploy
  script:
    - echo "This is the staging stage"
    - echo $PATH
    - bundle config
    - steps/deploy $STAGE_PATH $CI_RELEASE staging
  only:
    - stage