cache:
  paths:
    - vendor/bundle

before_script:
  - whoami
  - pwd
  - ruby -v
  - which ruby
  - ls -l
  - bundle install --path vendor/bundle

build:
  stage: build
  script:
    - echo "This is the build stage"

test:
  stage: test
  script:
    - echo "This is test stage"

staging:
  stage: deploy
  script:
    - echo "This is the staging stage"
    - cap staging deploy
  only:
    - stage